### ISSUE TITLE
Publish typescript declarations

### ISSUE THREAD

**Issue by paales** [adobe/apollo-link-mutation-queue#2]
It seems there is no `d.ts` file outputted along with the js file, is that something that can be done?

**Comment by paales** [comment]
This should probably be set to true: https://github.com/adobe/apollo-link-mutation-queue/blob/master/tsconfig.json#L3

**Comment by sirugh** [comment]
Seems simple enough - open a PR and I'll check it out when I get some time.

**Comment by sirugh** [comment]
As I'm new to typescript, for reference: https://www.typescriptlang.org/docs/handbook/compiler-options.html

> Generates corresponding .d.ts file.

:)

**Comment by paales** [comment]
@sirugh Can you change the code yourself, going through the agreement stuff for a single line seems bit absurd :)

**Comment by paales** [comment]
This one https://github.com/adobe/apollo-link-mutation-queue/pull/3

**Comment by sirugh** [comment]
Done and published.

#3
